<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-05-25 14:17

$extensionPath = t3lib_extMgm::extPath('mzvoting');
return array(
	'tx_mzvoting_pi1' => $extensionPath . 'pi1/class.tx_mzvoting_pi1.php',
	'tx_mzvoting_pi2' => $extensionPath . 'pi2/class.tx_mzvoting_pi2.php',
	'tx_mzvoting_recalc' => $extensionPath . 'scheduler/class.tx_mzvoting_recalc.php',
	'tx_mzvoting_sendmails' => $extensionPath . 'scheduler/class.tx_mzvoting_sendmails.php',
	'tx_mzvoting_sendmails_AdditionalFieldProvider' => $extensionPath . 'scheduler/class.tx_mzvoting_sendmails_AdditionalFieldProvider.php',
);

?>